sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JKgADjUbtAoE9xaIsY6Rw2IiBPF2mSNjKqv7FBoA5xEbugLP3jNp2Pcxnhy4+7fFvMnQWg3Hb8HXdScqXJX0q0LcMIthUSBSGc4f+onahP41Z67PHEjcBJHUCmv1Gq6UV40DRP6tEeW0n45bZ7bPWRJbioflbIY63AEQ5BT/zw78Zx/H0uqok/14lSHYebdJrj4UI47NBsO9b8sE0IPwaPsQhq9hLbJz0MgB7mloF2GvtvkLKZ8+2EwCjYMk0U5fkOxyuPYYmMvgJM1WDKc4Dij9NNnItvh1x2tl8NCJRNeqJ/VlWPNP2gC+r+TVMqQ5x0h3/dd8pQX+a/CNLNOPxgeyg+vPdk/cCrBV0ZdWxfpCjUXwzbNittaoNupQiIdrfQx6AgsEgj7NXdfVunSjCco7SFzeXkuGxvEX/yTWTCxNwfXf6pCRDeBRPwc1JCUMpUgzZIlvVM8Fc0K2JmytyDlac3poC6HEEEdiNulEe4cXecCDYl2PFeRPoqGel/AFGji43r6RkyD/hRwmOlGWXAwXfb3gwaVku6eaojWpoijPSQxoh+rR7mTFITC5Njy+nJRlvt6f1cEhNwv2RBfdMpMen+uGeg1vs14vqV9+VXgAXheA9r5y4CB/ZCH7HpzvW1j/aF5Z+KE1ehmenXYhHE8+hnWFK0ZZ9hr1KVyCmg4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-the-United-Netherlands-from-the-Death-of-William-the-Silent-to-the-Twelve-Year-s-Tr__4842
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy